package Exception_handl;

public class try_catch6 {
	public static void main(String[] args) {  
        
        try  
        {  
        int data1=50/0; 
  
        }  
            
        catch(Exception e)  
        {  
            
        int data2=50/0;    
  
        }  
    System.out.println("rest of the code");  
    }  
}
